### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by willemneal** [Inrupt-inc/generator-solid-angular#5] opened 2018-09-30 18:34 UTC
I was able to get around #3 with `ng serve --host 0.0.0.0 --disableHostCheck true`

Now I get:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://solid.community/.well-known/openid-configuration. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://localhost:4200’).

**Comment by james-martin-jd** [comment] 2018-10-23 19:46
Cannot reproduce personally, closing unless others raise the same issue

**Closed by james-martin-jd** 2018-10-23 19:46 UTC
Labels: bug, help wanted
